### PR TITLE
feat: components always available globally (hybrid loader)

### LINKED ISSUE #18: Watch is too slow
Not sure if it's a bug, but I have quiet a bit of components ~250 and seems like with more than 100 components watch takes ages, it's really really slow, I even tried to set watch: false for certain folders, but doesn't seems to be helping

**To Reproduce**
1. Have more than 100 components

### LINKED ISSUE #53: Template not scanned outside .vue files if imported via src
**Describe the bug**
If you import template using `<template src="./template.html">`, the file is not scanned for components. 

**To Reproduce**
- Create `index.vue` and `index.html` file
- Instead of writing markup into `<template>`, import the template using `<template src="./index.html">`
- => Components are not available

**Expected behavior**
The html template should be scanned for components and imported.

**Additional context**
I've added the `@nuxt/components` integration to [@inkline/inkline](https://github.com/inkline/inkline) and tested it out. Everything works well except for this. 

You can see it reproduced here: https://codesandbox.io/s/beautiful-sound-skdp6

### LINKED ISSUE #68: Load components found in string of HTML?
I have [built a component that is used to display content out of WordPress](https://github.com/funkhaus/fuxt/blob/master/components/WpContent.vue). Sometimes this content includes a Vue component, like `<shortcode-gallery/>` for example, and using a render function this component will actually render those Vue components from content in the CMS.

```
    render(h) {
        return h({
            template: `<div class="wp-content">${this.htmlTemplate}</div>`
        })
    }
```

This works great currently, but it has required me to pre-load all components that could be used in the CMS. Is there anyway I can use this plugin to help lazy-load components if they are present in a string of HTML?

I was thinking it could work like this:

```
watch: {
    htmlTemplate(newVal) {
      // newVal is a string of HTML, 
     // Now look to preload any components found in the string
      this.$components("loadComponents", newVal)
    }
}
```

It seems nuxt/components is geared around webpack, so this is probably not going to work how I imagine, but I thought I'd ask.

### LINKED ISSUE #88: Functional component with conditional child fails
**Describe the bug**
When using a conditional component within a functional component a `TypeError: _vm._v is not a function` is thrown

**To Reproduce**

See the test case commit I added on this branch: https://github.com/nuxt/components/commit/6aa9ea035ffde4ac297d32ec62ee861b5cbe6ba3

**Expected behavior**
That there would be no error

**Screenshots**
na

**Additional context**

I checked several things:
- the tag extractor seems to be working ok
- after adding a `_v` method (for debugging) in the `provideFunctionalComponent` method, you will get another error about `_e` not being a function.

Unfortunately thats all I managed to do, eg I dont fully understand where these `_c/v/e` names are originating from (is that some vue-loader thing?).

### LINKED ISSUE #91: Components are only imported if using single file components (doesnt work with independent .html files)
**Describe the bug**
Custom component from external package will automatically be imported in a single file component. In independent files it does not automatically import nor allow explicit import.

**Expected behavior**
Either expect to be able to import from the package as normal ( import ... from '...'  ) or auto import like in single file components.

### LINKED ISSUE #92: Module incompatible with recursive components
**Describe the bug**

I was using the nuxt global components module before this module came out. I have a few components which I am using recursively. Code below. That was working as I was naming the components as required by Vue to use them recursively. 

However, after upgrading to 2.14.3 and nuxt components modules, I am getting the below error for recursive components: 

Unknown custom element: <CaseObject> - did you register the component correctly? For recursive components, make sure to provide the "name" option

My components are still named. See the example below

```
<template>
   <div >
        <div
                v-for="(item2,propertyName2) in item"
                :key="propertyName2"
            >
               
            <p class="font-weight-bold title mt-5 primary--text" v-if="typeof item2 === 'object' && !property && !(item2 instanceof Date)">{{ propertyName2.replace(/_/g, ' ') | capitalize }}</p>

            <p class="font-weight-bold text--secondary" v-else-if="typeof item2 === 'object' && !(item2 instanceof Date)">{{ propertyName2.replace(/_/g, ' ') | capitalize }}</p>

            <CaseItem v-if="(typeof item2 !== 'object' && !Array.isArray(item2)) || (item2 instanceof Date)" :item='item2' :property="property ? `${property}.${propertyName2}` : propertyName2" />
            
            <CaseObject v-if="typeof item2 === 'object' && !Array.isArray(item2) && !(item2 instanceof Date)" :item="item2" :property="property ? `${property}.${propertyName2}` : propertyName2"/>
            
            <CaseArray v-if="Array.isArray(item2)" :item="item2" :property="property ? `${property}.${propertyName2}` : propertyName2"
                        />
                
        </div>
        
   </div>
</template>

<script>


export default {
    name: 'CaseObject',


```

**Expected behavior**
Components should work recursively

**Screenshots**

Screenshot 2020-08-23 at 12 08 53 AM

**Additional context**
Recursive components still working fine with the nuxt global components module

### PR DESCRIPTION
**Pull request by pi0**
With #43, we added support for `global: true` and introduced an  auto generated plugin that instead of loader strategy, globally registers components with async chunks. This option was disabled for 1-production to reduce network requests/size and allow webpack [smartly chunking](https://webpack.js.org/plugins/split-chunks-plugin/) per page and for 2-development to make behavior consistent with production and being aware if a component cannot work with loader.

It is proved that loader approach is not good for DX both for dev performance and limitations for detecting components. On the other hands without loader prod build is not optimized.

Approach of this PR is to globally register all components (async loaded) but when loader detects component usage per page, directly imports them (vue pick `components: {}` option over global one). This mixed approach brings best of two worlds.

Resolves #53,  resolves #92, resolves #91, resolves #88, resolves #68 and resolves #18 (loader)

**Slightly breaking change:** Components without `Lazy` prefix, are sync imports which might break some custom usages.

**Slightly breaking change:** Without loader, functional components cannot have functional children. This is probably more a Vue.js bug since functional components use `__ssrRender` of their parent's context and functional parent has no context
## TODO

- [x] Disable loader for development (customizable via `components.loader` to force enable or disable)
- [x] ~~Deprecate `global` option as we always do it~~ (silently deprecate to avoid side-effects)
- [x] Update tests
- [x] Update docs

### CODE REVIEW

**Comment by lukasborawski** [comment]
@pi0 when can we expect a merge of this one? It's solving a lot of issues, especially #92 ... Thanks.

**Comment by vampics** [comment]
+1

**Review by Atinux — APPROVED** [review]

**Comment by pi0** [comment]
Feature is likely be released as a major version of `@nuxt/components` for `nuxt@2.15`

**Comment by LeCoupa** [comment]
Thanks @pi0 🙏
